[project]
site_name = "Pianola"
site_author = "Tremeschin"
site_description = "🎹 Smoothest piano roll visualizer"
site_url  = "https://pianola.tremeschin.com/"
repo_url  = "https://github.com/BrokenSource/Pianola/"
repo_name = "BrokenSource/Pianola"
docs_dir  = "website"
nav = [
  {Origin = "https://tremeschin.com/"},
  {Home = [
    "index.md",
  ]},
]

[project.theme]
name = "zentheme"
favicon = "assets/images/logo.png"

[project.theme.icon]
logo = "material/piano"
repo = "fontawesome/brands/github"

[[project.extra.social]]
name = "Discord"
icon = "fontawesome/brands/discord"
link = "https://discord.gg/KjqvcYwRHm"

[[project.extra.social]]
name = "Patreon"
icon = "fontawesome/brands/patreon"
link = "https://www.patreon.com/Tremeschin"

[[project.extra.social]]
name = "GitHub"
icon = "fontawesome/brands/github"
link = "https://github.com/Tremeschin"

[[project.extra.social]]
name = "YouTube"
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@Tremeschin"
